name: brew test-bot
on:
  pull_request_target:
    branches:
      - main
    paths:
      # Only run this for changes to the formulas
      - "Formula/*.rb"
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/overmindtech/overmind
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        # Do not upgrade to v4 due to https://github.com/actions/upload-artifact/issues/478
        # Homebrew will need to solve this in the `brew pr-pull` command. We
        # have disabled rennovate for this repo to stop this gettung upgraded
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
  auto-merge:
    runs-on: ubuntu-latest
    needs: test-bot
    permissions: 
      contents: write
      pull-requests: write
      issues: write
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - name: Check if PR is approved
        id: check_approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const approved = reviews.some(review => review.state === 'APPROVED');
            return { approved: approved };

      # Tag this PR with pr-pull label only if it has been approved
      - name: Tag PR with pr-pull label
        if: ${{ steps.check_approval.outputs.approved == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pr-pull']
            });