name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - run: brew test-bot --only-formulae --root-url=https://ghcr.io/v2/overmindtech/overmind
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        # Do not upgrade to v4 due to https://github.com/actions/upload-artifact/issues/478
        # Homebrew will need to solve this in the `brew pr-pull` command. We
        # have disabled rennovate for this repo to stop this gettung upgraded
        uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: '*.bottle.*'
  auto-merge:
    runs-on: ubuntu-latest
    needs: test-bot
    permissions: 
      contents: write
      pull-requests: write
      issues: write
    if: github.event_name == 'pull_request'
    steps:
      # Combined Validation to make sure that we only auto-label on PRs that bump the version and nothing else
      - name: Validate PR and File Content
        id: validate
        run: |
          set -e
          # By default, set validation to pass
          VALIDATION_STATUS=pass
          
          # Validate the number of changed files
          if [ $(git diff --name-only HEAD^ HEAD | wc -l) -ne 1 ]; then
            echo "More than one file changed"
            VALIDATION_STATUS=fail
          else
            # Validate the specific file change
            if [ $(git diff --name-only HEAD^ HEAD | grep -c "Formula/overmind-cli.rb") -ne 1 ]; then
              echo "File changed is not Formula/overmind-cli.rb"
              VALIDATION_STATUS=fail
            fi

            # Validate file content
            if ! grep -qE '^  url "https://github.com/overmindtech/cli/archive/refs/tags/v[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz"$' Formula/overmind-cli.rb; then
              echo "File does not contain correct URL format"
              VALIDATION_STATUS=fail
            fi
          fi

          # Set the output
          echo "validation_status=$VALIDATION_STATUS" >> "$GITHUB_OUTPUT"

      # Tag this PR with pr-pull label only if validation passed
      - name: Tag PR with pr-pull label
        if: steps.validate.outputs.validation_status == 'pass'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pr-pull']
            })

      # Log message if validation failed but step marked as succeeded
      - name: Log validation result
        if: steps.validate.outputs.validation_status == 'fail'
        run: echo "Validation failed, skipping label addition but marking step as success"